/**
 * Autogenerated local (chainId 31337) overlay — do not edit by hand.
 *
 * This file is gitignored: your local deployment addresses live here and
 * should not be committed. Run `pnpm generate` after `pnpm deploy:localhost`
 * to refresh, or after a fresh clone to materialize a stub.
 */
import type { ContractDeployment } from "~~/utils/contract";

export const FHECounter = {} as const satisfies Partial<
  Record<number, ContractDeployment>
>;
